version: '3'

services:
  database:
    image: postgres:13.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - oddp_dev
    networks:
      - oddp_dev

volumes:
  oddp_dev:

networks:
  oddp_dev: