spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/odd
    username: odd
    password: odd_password
  jooq:
    sql-dialect: postgres
  codec:
    max-in-memory-size: 20MB
#  security:
#    oauth2:
#      client:
#        registration:
#          cognito:
#            client-id:
#            client-secret:
#            scope:
#            redirect-uri:
#            client-name:
#        provider:
#          cognito:
#            issuerUri:
#            user-name-attribute:

auth:
  enabled: false

management:
  endpoints:
    enabled: false
    web:
      base-path: /
  info:
    enabled: true
  health:
    enabled: true

logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: trace
      jooq:
        tools:
          LoggerListener: info
